FROM ccr.ccs.tencentyun.com/zhuiyi_docker_list/java8:aiforce
ADD ./mysql-connector-java-5.1.46-bin.jar /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext
ADD ./*.jar /entrypoint.d/
ADD ./entrypoint.d /entrypoint.d
