spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:log4jdbc:mysql://127.0.0.1:3306/ds_learn_business?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
          #          url: jdbc:log4jdbc:mysql://10.4.1.190:3339/ds_learn_business?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
          username: root
          password: 123456
          driverClassName: net.sf.log4jdbc.DriverSpy
#  resources:
#    static-locations:
#      - file:D://learn-download/
#  mvc:
#    static-path-pattern: /audio/**

mybatis:
  mapper-locations: classpath:mybatis/*.xml

excel:
  downLoadExcelUrl: d:/learn-download

ttsurl: /data/learn-tts/
educationPageSize: 1

examResultPushHost: https://aia.dev15.edusoho.cn
jwtPublicKey: -----BEGIN PUBLIC KEY-----MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC1tTOM1UNbm1b9H/fzaLvTgRIgD+LTxys9gmll1KfptzMWMVBzifp3w1ztxZ3SFOLm6SWYdLY9II3MfWt4of6srGSH+H94Odn+Cb5KbREz4YE3VpjP3On7MHda8OrQVjDVIjsZu49fOomEA+/Df47Ze6b9e5+DUmzvGDC82ZlKqQIDAQAB-----END PUBLIC KEY-----
jwtPrivateKey: -----BEGIN PRIVATE KEY-----MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALW1M4zVQ1ubVv0f9/Nou9OBEiAP4tPHKz2CaWXUp+m3MxYxUHOJ+nfDXO3FndIU4ubpJZh0tj0gjcx9a3ih/qysZIf4f3g52f4JvkptETPhgTdWmM/c6fswd1rw6tBWMNUiOxm7j186iYQD78N/jtl7pv17n4NSbO8YMLzZmUqpAgMBAAECgYEAjEkCLJe1sjLi3PficT0JzcfXW4OIRqJ9Arb9ck3U+T6kJV0bVKhRBEeDJlssdjYD2+xiRyrMS7MnZpnp8C95Mz6+lEmpdPAy53kjqquDlb5C9LvXO3u0jPrpXsOiRDFeTsXBmg2Pl9fsR4W5NYPoFO8B44L7Dddm+TV7TUkmrpECQQDo4vyjFvc/UPjJd4PLj6ZqwGauDX6zqS2HdZHwxjIr4CoV7xW4oHcoTSMylSU9yWX777xDL9E4UQsBWlK19QZ1AkEAx73mYn+olPCC0I4Tm0bDkRwvqxl269HG/9pgrpPHIncUcF5fcUT7twqMkrZrDFlhEPzWL34/fB02p4JDw9f05QJABk+gaQsGSED5fPwwJiQObnYoUi8rb9L12OXmvo+gbG/2tAF2pTo0AHOWsJg6GiKLEPi+MVPqZ4xKsA6yjxvEwQJAaqUCj86XBMaRIabp4vraSezhqpnS+7+qX0qKWkt+g/FOUVyh2sk5GBaizWZmK1bBU5+bAAqI/MxgNPmBEtyH3QJBANBOIdYtFG0ch70BdrSSTiBlZyMGC8Sr643XqoblTinIa5tg0sfXLPGfCkKd+x6jjBqIwP9+aAIS4auYEdrnpew=-----END PRIVATE KEY-----

education:
  isPushEducation: false
  address: 172.16.20.146:8090
dfs:
  open: false
  url: http://tame-dfs-test.rd-bj-env.wezhuiyi.com/
  supportType: local
